# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in mini_lisp.gemspec
gemspec

gem 'rainbow'
gem 'rake', '~> 13.0'

group :development do
  gem 'rbs'
  gem 'rubocop'
  gem 'steep'
  gem 'typeprof'
end
