# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in mini_lisp.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rainbow"

group :development do
  gem "rbs"
  gem "steep"
  gem "typeprof"
end

